export const IS_TEXT_EMPTY = 'IS_TEXT_EMPTY';
export const HOVER_TEXT_FORM = 'HOVER_TEXT_FORM';
export const OUT_TEXT_FORM = 'OUT_TEXT_FORM';
export const HOVER_BUTTON_FORM = 'HOVER_BUTTON_FORM';
export const OUT_BUTTON_FORM = 'OUT_BUTTON_FORM';
export const CONFIRMED_INPUT = 'CONFIRMED_INPUT';

